const bodyPartMap: Record<string, string> = {
  'Abs': '腹部',
  'Arms': '手臂',
  'Back': '背部',
  'Butt/Hips': '臀髋',
  'Chest': '胸部',
  'Full Body/Integrated': '全身/综合',
  'Legs - Calves and Shins': '小腿与胫骨',
  'Legs - Thighs': '大腿',
  'Neck': '颈部',
  'Shoulders': '肩部',
}

const muscleMap: Record<string, string> = {
  'Abs': '腹肌',
  'Adductors': '内收肌群',
  'Anterior Deltoids': '前三角肌',
  'Anconeus': '肘肌',
  'Biceps': '肱二头肌',
  'Brachialis': '肱肌',
  'Brachioradialis': '肱桡肌',
  'Calves': '小腿肌群',
  'Core': '核心肌群',
  'Deltoids': '三角肌',
  'Erector Spinae': '竖脊肌',
  'Gastrocnemius': '腓肠肌',
  'Gluteus Maximus': '臀大肌',
  'Gluteus Medius': '臀中肌',
  'Hamstrings': '腘绳肌',
  'Latissimus Dorsi': '背阔肌',
  'Obliques': '腹斜肌',
  'Pectorals': '胸大肌',
  'Quadriceps': '股四头肌',
  'Rectus Abdominis': '腹直肌',
  'Rhomboids': '菱形肌',
  'Rotator Cuff': '肩袖肌群',
  'Serratus Anterior': '前锯肌',
  'Soleus': '比目鱼肌',
  'Sternocleidomastoid': '胸锁乳突肌',
  'Tibialis Anterior': '胫骨前肌',
  'Transverse Abdominis': '腹横肌',
  'Trapezius': '斜方肌',
  'Triceps': '肱三头肌',
  'Upper Chest': '上胸',
  'Upper Trapezius': '上斜方肌',
}

// 全量精确中文名映射（覆盖 ACE 动作库所有动作）
const exactExerciseNameMap: Record<string, string> = {
  // ── Advanced ──────────────────────────────────────────
  'Agility Ladder: Lateral Shuffle': '敏捷梯：侧向滑步',
  'Alternate Leg Push-off': '交替腿蹬台阶',
  'Asynchronous Waves': '交替波浪绳',
  'Back Squat': '杠铃背蹲',
  'Barbell Jammers': '杠铃冲击推',
  'Bent-over Row': '俯身杠铃划船',
  'BOSU Lateral Jumps': 'BOSU 侧跳',
  'Bottom-up Press': '壶铃底朝上推举',
  'Bulgarian Split Squat': '保加利亚分腿蹲',
  'Burpee': '波比跳',
  'Clean and Press': '高翻推举',
  'Deadlift': '硬拉',
  'Double Push-press': '双壶铃借力推举',
  'Double Rotation Waves': '双绳旋转波浪',
  'Forward Lunge with Arm Drivers': '前弓步配合手臂摆动',
  'Front Squat to Overhead Press': '前蹲接过顶推举',
  'Glute Activation Lunges': '臀肌激活弓步',
  'Halo': '壶铃绕头光环',
  'Hang Clean': '悬垂高翻',
  'Hexagon Drill': '六边形敏捷跑',
  'High Plank T-spine Rotation': '高位平板支撑胸椎旋转',
  'High Windmill': '高风车（持铃）',
  'Inchworms': '毛毛虫爬行',
  'Inverted Flyers': '单腿倒飞鸟',
  'Kneeling Wood Chop': '跪姿伐木',
  'Lateral Lunge Wood Chop': '侧弓步伐木',
  'Lateral Waves': '侧向波浪绳',
  'Lateral Zig Zags': '侧向锯齿跑',
  'Low Windmill': '低风车（持铃）',
  'Lunge to Single Arm Row': '弓步接单臂划船',
  'Lunge with Overhead Press': '弓步配合过顶推举',
  'Medicine Ball Lunge to Chest Pass': '药球弓步接胸前传球',
  'Medicine Ball Push-ups': '药球俯卧撑',
  'Mountain Climbers': '登山跑',
  'Multidirectional Ladder Drill': '多方向梯形钻',
  'Offset Single-arm Chest Press': '错位单臂卧推',
  'Pistol Squat Workout': '单腿深蹲',
  'Power Clean': '爆发力高翻',
  'Power Push Down': '爆发力下推',
  "Prone ABC's": '俯卧 ABC 稳定球练习',
  'Prone Runner': '俯卧稳定球跑步模拟',
  'Pull to Press': '拉接推举',
  'Push Jerk': '借力挺举（杠铃）',
  'Push Press': '借力推举',
  'Push-jerk': '壶铃借力挺举',
  'Push-up with Single-leg Raise': '单腿抬高俯卧撑',
  'Push-up with Staggered Hands': '错位手俯卧撑',
  'Renegade Row': '俯撑交替哑铃划船',
  'Reverse Lunge with Rotation': '后弓步配合旋转',
  'Roll Out': '杠铃滚出',
  'Rotational Overhead Press': '旋转过顶推举',
  'Rotational Slam': '旋转药球砸地',
  'Russian Twist': '俄罗斯转体',
  'Side Plank (Modified)': '侧平板支撑（简化）',
  'Side Plank Row': '侧平板支撑划船',
  'Side-lying Arm Rolls': '侧卧手臂环绕',
  'Simultaneous Wave with Reverse Lunges': '同步波浪绳配合后弓步',
  'Simultaneous Waves': '同步波浪绳',
  'Single Arm Overhead Squat': '单臂过顶深蹲',
  'Single Arm Swing': '单臂壶铃摆荡',
  'Single Arm, Single Leg Plank': '单臂单腿平板支撑',
  'Single Leg Hamstring Curl': '单腿稳定球腿弯举',
  'Single Leg Romanian Dead Lift': '单腿罗马尼亚硬拉（阻力带）',
  'Single-arm Medicine Ball Push-up': '单臂药球俯卧撑',
  'Single-arm Rotational Press': '单臂旋转推举',
  'Single-arm, Single-leg Romanian Dead Lift': '单臂单腿罗马尼亚硬拉',
  'Single-leg Romanian Deadlift': '单腿罗马尼亚硬拉',
  'Single-leg Stand with Reaches': '单腿站立触碰',
  'Snatch': '抓举',
  'Spinal Twist with a Push-Pull Movement': '脊柱旋转推拉',
  'Squat to Overhead Press': '深蹲接过顶推举',
  'Stability Ball Knee Tucks': '稳定球屈膝收腹',
  'Stability Ball Pikes': '稳定球倒 V 撑',
  'Stability Ball Reverse Extensions': '稳定球反向背伸',
  'Standing Hay Baler': '站姿药球打捆',
  'Standing Rotational Chop': '站姿旋转砍木',
  'Standing Shoulder Press': '站姿杠铃推举',
  'Standing Single-leg Cable Rotation': '站姿单腿绳索旋转',
  'Standing Wood Chop': '站姿伐木',
  'Supine Suitcase Pass': '仰卧稳定球传递',
  'T Drill': 'T 型敏捷跑',
  'Transverse Lunge': '横向弓步',
  'Transverse Lunge to Single Arm Row': '横向弓步接单臂划船',
  'TRX Atomic Push-up': 'TRX 原子俯卧撑',
  'TRX Back Row': 'TRX 背部划船',
  'TRX Biceps Curl': 'TRX 二头弯举',
  'TRX Chest Press': 'TRX 胸部推举',
  'TRX Front Rollout': 'TRX 前向滚出',
  'TRX Hamstrings Curl': 'TRX 腿弯举',
  'TRX Hip Press': 'TRX 髋部推举',
  'TRX Lunge': 'TRX 弓步',
  'TRX Mountain Climber': 'TRX 登山跑',
  'TRX Oblique Crunch': 'TRX 斜腹卷腹',
  'TRX Overhead Squat': 'TRX 过顶深蹲',
  'TRX Pendulum': 'TRX 钟摆',
  'TRX Pike': 'TRX 倒 V 撑',
  'TRX Plank': 'TRX 平板支撑',
  'TRX Power Pull': 'TRX 爆发力拉',
  'TRX Pushup': 'TRX 俯卧撑',
  'TRX Row': 'TRX 划船',
  'TRX Rocker': 'TRX 摇摆',
  'TRX Side Plank': 'TRX 侧平板支撑',
  'TRX Sprinter Start': 'TRX 起跑姿势',
  'TRX Squat': 'TRX 深蹲',
  'TRX Triceps Press': 'TRX 三头推举',
  'TRX Y-Fly': 'TRX Y 字飞鸟',
  'Turkish Get-up': '土耳其起身',
  'Two-point Plank': '两点支撑平板',
  'Uppercut': '上勾拳',

  // ── Intermediate ──────────────────────────────────────
  'Alternating Lateral Lunge': '交替侧弓步',
  'Alternating Medicine Ball Push-up': '交替药球俯卧撑',
  'Barbell Hip Thrust': '杠铃臀推',
  'Bear Crawl': '熊爬',
  'Bent-knee Dead Lift': '屈膝硬拉',
  'Bicycle Crunch': '自行车卷腹',
  'Bird-dog': '鸟狗式',
  'Box Jump': '跳箱',
  'Cable Hip Abduction': '绳索髋外展',
  'Calf Raise': '提踵',
  'Chest Press': '卧推',
  'Chin-ups': '引体向上（正握）',
  'Cobra Exercise': '眼镜蛇式',
  'Dead Bug': '死虫式',
  'Decline Plank': '下斜平板支撑',
  'Double-leg Lowering with Bent Knee': '屈膝双腿下放',
  'Dumbbell Bench Press': '哑铃卧推',
  'Dumbbell Bent-over Row': '哑铃俯身划船',
  'Dumbbell Bicep Curl': '哑铃二头弯举',
  'Dumbbell Curl': '哑铃弯举',
  'Dumbbell Deadlift': '哑铃硬拉',
  'Dumbbell Fly': '哑铃飞鸟',
  'Dumbbell Front Raise': '哑铃前平举',
  'Dumbbell Lateral Raise': '哑铃侧平举',
  'Dumbbell Lunge': '哑铃弓步',
  'Dumbbell Romanian Deadlift': '哑铃罗马尼亚硬拉',
  'Dumbbell Shoulder Press': '哑铃肩推',
  'Dumbbell Squat': '哑铃深蹲',
  'Dumbbell Step-up': '哑铃登台阶',
  'Dumbbell Triceps Kickback': '哑铃三头后踢',
  'Elbow Plank': '肘撑平板支撑',
  'Face Pull': '绳索面拉',
  'Glute Bridge': '臀桥',
  'Goblet Squat': '高脚杯深蹲',
  'Good Morning': '早安式',
  'Hammer Curl': '锤式弯举',
  'Hip Extension': '髋伸展',
  'Hip Flexor Stretch': '髋屈肌拉伸',
  'Incline Dumbbell Press': '上斜哑铃卧推',
  'Jump Squat': '跳跃深蹲',
  'Jumping Jack': '开合跳',
  'Kettlebell Deadlift': '壶铃硬拉',
  'Kettlebell Swing': '壶铃摆荡',
  'Lateral Band Walk': '侧向弹力带行走',
  'Lateral Lunge': '侧弓步',
  'Lateral Raise': '侧平举',
  'Lat Pulldown': '高位下拉',
  'Leg Curl': '腿弯举',
  'Leg Extension': '腿屈伸',
  'Leg Press': '腿举',
  'Leg Raise': '悬垂举腿',
  'Lying Leg Curl': '俯卧腿弯举',
  'Medicine Ball Slam': '药球砸地',
  'Medicine Ball Squat to Press': '药球深蹲接推举',
  'Military Press': '军式推举',
  'Monster Walk': '怪物走',
  'Mountain Climber': '登山跑（单人）',
  'Nordic Hamstring Curl': '北欧弯举',
  'Overhead Press': '过顶推举',
  'Overhead Squat': '过顶深蹲',
  'Pallof Press': '帕洛夫推举',
  'Plank': '平板支撑',
  'Plank Hip Dip': '平板支撑髋部下沉',
  'Plank Shoulder Tap': '平板支撑肩部点触',
  'Pull-up': '引体向上',
  'Push-up': '俯卧撑',
  'Resistance Band Pull Apart': '弹力带拉开',
  'Reverse Crunch': '反向卷腹',
  'Reverse Fly': '俯身飞鸟',
  'Reverse Lunge': '后弓步',
  'Romanian Deadlift': '罗马尼亚硬拉',
  'Romanian Dead Lift': '罗马尼亚硬拉',
  'Seated Cable Row': '坐姿绳索划船',
  'Seated Dumbbell Curl': '坐姿哑铃弯举',
  'Seated Row': '坐姿划船',
  'Side Plank': '侧平板支撑',
  'Side-lying Hip Abduction': '侧卧髋外展',
  'Single Leg Glute Bridge': '单腿臀桥',
  'Single-leg Calf Raise': '单腿提踵',
  'Skull Crusher': '仰卧臂屈伸（折头）',
  'Squat': '深蹲',
  'Standing Barbell Curl': '站姿杠铃弯举',
  'Standing Calf Raise': '站姿提踵',
  'Step-up': '登台阶',
  'Sumo Deadlift': '相扑硬拉',
  'Superman': '超人式',
  'Triceps Dip': '三头臂屈伸',
  'Triceps Pressdown': '三头下压',
  'Upright Row': '直立划船',
  'Wall Sit': '靠墙静蹲',

  // ── Beginner ──────────────────────────────────────────
  'Bodyweight Squat': '徒手深蹲',
  'Bridge': '臀桥',
  'Cat-Cow': '猫牛式',
  'Chair Squat': '椅子深蹲',
  'Child Pose': '婴儿式',
  'Crunch': '卷腹',
  'Downward Dog': '下犬式',
  'Fire Hydrant': '消防栓式',
  'Flutter Kick': '颤腿',
  'Glute Kickback': '臀部后踢',
  'High Knees': '高抬腿',
  'Hip Circle': '髋部环绕',
  'Hip Hinge': '髋铰链',
  'Knee Push-up': '跪姿俯卧撑',
  'March in Place': '原地踏步',
  'Modified Push-up': '简化俯卧撑',
  'Pigeon Pose': '鸽子式',
  'Prone Hip Extension': '俯卧髋伸展',
  'Shoulder Bridge': '肩桥',
  'Standing Hip Abduction': '站姿髋外展',
  'Toe Touch': '触脚趾',
  'Warrior I': '战士一式',
  'Warrior II': '战士二式',
  'Wall Push-up': '墙壁俯卧撑',
  'Seated Leg Raise': '坐姿抬腿',

  // ── TRX 补全 ──────────────────────────────────────────
  'TRX Overhead Triceps Extension': 'TRX 过顶三头伸展',
  'TRX Side-straddle Golf Swings': 'TRX 侧跨步高尔夫挥杆',
  'TRX Single-arm Chest Press': 'TRX 单臂推胸',
  'TRX Single-arm Row': 'TRX 单臂划船',
  'TRX Suspended Knee Tucks': 'TRX 悬吊屈膝收腹',
  'TRX Suspended Lunge': 'TRX 悬吊弓步',
  'TRX Suspended Pike': 'TRX 悬吊倒 V 撑',
  'TRX Suspended Push-up': 'TRX 悬吊俯卧撑',

  // ── 壶铃补全 ──────────────────────────────────────────
  "Waiter's Carry": '侍者托举行走',
  'Figure Eight': '壶铃 8 字绕行',
  'Half Turkish Get-up': '半土耳其起身',

  // ── Seated 机械/哑铃 补全 ──────────────────────────────
  'Seated Bent-Knee Biceps Stretch': '坐姿屈膝二头拉伸',
  'Seated Biceps Curl': '坐姿二头弯举',
  'Seated Butterfly Stretch': '坐姿蝴蝶式拉伸',
  'Seated Cable Press': '坐姿绳索推举',
  'Seated Calf Stretch': '坐姿小腿拉伸',
  'Seated Chest Press': '坐姿器械推胸',
  'Seated Close-Grip Chest Press': '坐姿窄握器械推胸',
  'Seated Crunch': '坐姿器械卷腹',
  'Seated Decline Cable Press': '坐姿下斜绳索推举',
  'Seated High Back Row': '坐姿高位背部划船',
  'Seated High Back Rows': '坐姿高位背部划船（器械）',
  'Seated Incline Cable Press': '坐姿上斜绳索推举',
  'Seated Lat Pulldown': '坐姿高位下拉',
  'Seated Leg Extension': '坐姿腿屈伸',
  'Seated Leg Press Exercise': '坐姿腿举',
  'Seated Machine Close-Grip Shoulder Press': '坐姿器械窄握肩推',
  'Seated Medicine Ball Trunk Rotations': '坐姿药球躯干旋转',
  'Seated Shoulder Press': '坐姿器械肩推',
  'Seated Side-Straddle Stretch': '坐姿侧跨腿拉伸',
  'Seated Straddle Stretch': '坐姿跨腿拉伸',
  'Seated Toe Touches': '坐姿触脚趾',

  // ── Supine 仰卧系列补全 ────────────────────────────────
  'Supine 90-90 Hip Rotator Stretch': '仰卧 90-90 髋旋转拉伸',
  'Supine Dead Bug': '仰卧死虫式',
  'Supine Hamstrings Stretch': '仰卧腘绳肌拉伸',
  'Supine Hip Flexor Stretch': '仰卧髋屈肌拉伸',
  'Supine Hollowing with Lower Extremity Movements': '仰卧腹部收缩配合下肢动作',
  'Supine Pelvic Tilts': '仰卧骨盆倾斜',
  'Supine Reverse Marches': '仰卧反向踏步',
  'Supine Rotator Cuff': '仰卧肩袖训练',
  'Supine Shoulder Flexion': '仰卧肩屈曲',
  'Supine Snow Angel (Wipers) Exercise': '仰卧雪天使（雨刮器）',

  // ── Beginner 徒手/拉伸补全 ────────────────────────────
  '90 Lat Stretch': '90° 背阔肌拉伸',
  'Ankle Flexion': '踝关节屈曲',
  'Anti-rotation Reverse Lunge': '抗旋转后弓步',
  'Bent Knee Push-up': '屈膝俯卧撑',
  'Childs Pose': '婴儿式',
  'Contralateral Limb Raises': '对角线肢体抬高',
  'Dirty Dog': '脏狗式（侧抬腿）',
  'Forward Hurdle Run': '前向跨栏跑',
  'Forward Linear Jumps': '前向直线跳',
  'Forward Stepping over Cones': '前向跨锥步',
  'Front Raise': '前平举',
  'Glute Bridge Exercise': '臀桥',
  'Glute Press': '器械臀部推举',
  'Half-kneeling Hay Baler': '半跪姿打捆式',
  'Incline Chest Press': '上斜卧推',
  'Incline Reverse Fly': '上斜俯身飞鸟',
  "Kneeling ABC's": '跪姿 ABC 稳定球',
  'Kneeling Hip-flexor Stretch': '跪姿髋屈肌拉伸',
  'Kneeling Lat Stretch (w/bench)': '跪姿背阔肌拉伸（借凳）',
  'Kneeling TA Stretch': '跪姿 TA 拉伸',
  'Lateral Neck Flexion': '颈侧屈',
  'Lateral Shoulder Raise': '器械侧平举',
  'Lateral Shuffles': '侧向滑步',
  'Leg Crossover Stretch': '交叉腿拉伸',
  'Lying Hamstrings Curl': '卧姿腘绳肌弯举',
  "Modified Hurdler's Stretch": '简化跨栏拉伸',
  'Neck Flexion and Extension': '颈部前屈后伸',
  'Overhead Triceps Stretch': '过顶三头肌拉伸',
  'Partner Assisted Bodyweight Squats': '搭档辅助深蹲',
  'Partner Tricep Extension': '搭档三头伸展',
  'Prone (Lying) Hamstrings Curl': '俯卧腘绳肌弯举',
  'Quadruped Bent-knee Hip Extensions': '四足屈膝髋伸展',
  'Rotator Cuff External Rotation': '肩袖外旋',
  'Rotator Cuff Internal Rotation': '肩袖内旋',
  'Shoulder Packing': '肩胛骨下沉训练',
  'Side Lying Hip Abduction': '侧卧髋外展',
  'Side Lying Hip Adduction': '侧卧髋内收',
  'Side Lying Quadriceps Stretch': '侧卧股四头肌拉伸',
  'Side Plank - modified': '侧平板支撑（简化版）',
  'Single Leg Push-off': '单腿蹬台阶',
  'Single Leg Stand': '单腿站立',
  'Single-arm Lateral Raise': '单臂侧平举',
  'Squat Jump': '深蹲跳',
  'Squat Jumps': '深蹲跳',
  'Stability Ball Sit-ups / Crunches': '稳定球仰卧起坐/卷腹',
  'Stability Ball Wall Squats': '稳定球靠墙深蹲',
  'Standing Bicep Curl': '站姿二头弯举',
  'Standing Calf Raises - Wall': '靠墙站姿提踵',
  'Standing Chest Stretch': '站姿胸部拉伸',
  'Standing Crunch': '站姿卷腹',
  'Standing Dorsi-Flexion (Calf Stretch)': '站姿背屈（小腿拉伸）',
  'Standing Lunge Stretch': '站姿弓步拉伸',
  'Standing Shoulder Extension': '站姿肩伸展',
  'Supermans': '超人式',
  'Thomas Stretch': '托马斯拉伸',
  'Tricep Extension': '三头伸展（器械）',
  'Tricep Pressdown Exercise': '三头下压',
  'Triceps Kickback': '三头后踢腿',
  'Triceps Pushdowns': '三头器械下压',
  'Upward Facing Dog': '上犬式',
  'V Sit Partner Rotations': 'V 坐姿搭档旋转',
  'V-raise': 'V 字上举',
  'Walking Abduction': '行走外展',
  'Wrist Curl - Extension': '腕伸展',
  'Wrist Curl - Flexion': '腕弯举',
  'Wrist Supination & Pronation Exercises': '腕旋转练习',

  // ── Intermediate 补全 ──────────────────────────────────
  'Bear Crawl Exercise': '熊爬',
  'Bicep Curl': '二头弯举',
  'BOSU Squat Jumps': 'BOSU 深蹲跳',
  'Box Jumps': '跳箱',
  'Calf Raises': '杠铃提踵',
  'CKC Parascapular Exercises': '闭链肩胛旁肌训练',
  'Close-grip Bench Press': '窄距卧推',
  'Cycled Split-Squat Jump': '交替分腿跳',
  'Diagonal Raise': '对角线上举',
  'Downward-facing Dog': '下犬式',
  'Elevated Glute Bridge': '抬高臀桥',
  "Farmer's Carry": '农夫行走',
  'Forward Cone Jumps': '前向跨锥跳',
  'Forward Linear Ladder Drill': '前向直线梯钻',
  'Forward Lunge': '前弓步',
  'Front Plank': '前侧平板支撑',
  'Front Squat': '前蹲',
  'Glute Bridge Single Leg Progression': '单腿臀桥进阶',
  'High Row': '高位划船',
  'High-low Partner See-saw': '高低搭档跷跷板',
  'Hip Bridge': '杠铃髋桥',
  'Hip Rotations (Push-up Position)': '俯撑髋旋转',
  'Jump and Reach': '跳跃触摸',
  'Kneeling Hay Baler': '跪姿打捆式',
  'Kneeling Lat Pulldown': '跪姿高位下拉',
  'Kneeling Reverse Fly': '跪姿俯身飞鸟',
  'Lateral Cone Jumps': '侧向跨锥跳',
  'Lateral Crawls': '侧向爬行',
  'Lateral Hurdle Run': '侧向跨栏跑',
  'Lateral Over Unders': '侧向绕过障碍',
  'Lunge': '弓步',
  'Lunge with Elbow Instep': '弓步配合肘触脚背',
  'Lying Barbell Triceps Extensions': '仰卧杠铃三头伸展',
  'Lying Chest Fly': '仰卧哑铃飞鸟',
  'Lying Pullovers': '仰卧哑铃下拉',
  'Overhead Medicine Ball Throws': '药球过顶抛',
  'Overhead Slams': '药球过顶砸地',
  'Partner Standing Row with Resistance Tubing': '搭档站姿弹力带划船',
  'Plank with Knee Drag': '平板支撑膝盖拖拉',
  'Plank-ups': '平板支撑撑起',
  'Prone Scapular (Shoulder) Stabilization Series - I, Y, T, W, O Formation': '俯卧肩胛稳定系列（IYTWO）',
  'Pull-over Crunch': '壶铃下拉卷腹',
  'Pull-ups': '引体向上',
  'Reverse Bicep Curl': '反握弯举',
  'Reverse Ab Crunch': '反向卷腹',
  'Reverse Slam': '药球反向砸地',
  'Rotational Uppercut': '旋转上勾拳',
  'Seated Overhead Press': '坐姿过顶推举',
  'Seated Straddle with Side Reaches': '坐姿跨腿侧伸',
  'Shoulder Stability-Mobility Series - I, Y, T, W Formations': '肩稳定灵活系列（IYTW）',
  'Shrug': '耸肩',
  'Side Lunge': '侧弓步',
  'Side Plank with Straight Leg': '直腿侧平板支撑',
  'Single Arm Overhead Press': '单臂过顶推举',
  'Single Arm Plank': '单臂平板支撑',
  'Single Arm Row': '单臂划船',
  'Single Leg Squat': '单腿深蹲',
  'Single-arm Chest Press': '单臂推胸',
  'Single-arm Row': '单臂哑铃划船',
  'Spider Walks': '蜘蛛爬行',
  'Sprinter Pulls': '短跑拉伸',
  'Squat to Overhead Raise': '深蹲接过顶上举',
  'Squat to Row': '深蹲接划船',
  'Stability Ball Hamstring Curl': '稳定球腿弯举',
  'Stability Ball Prone Walkout': '稳定球俯卧走出',
  'Stability Ball Push-Up': '稳定球俯卧撑',
  'Stability Ball Shoulder Stabilization': '稳定球肩部稳定',
  'Standing Ankle Mobilization': '站姿踝关节活动',
  'Standing Anti-rotation Press': '站姿抗旋转推举',
  'Standing Chest Fly': '站姿绳索飞鸟',
  'Standing Decline Cable Flyes': '站姿下斜飞鸟',
  'Standing Gate Openers (Frankensteins)': '站姿开门式（弗兰肯斯坦）',
  'Standing Hamstrings Curl': '站姿腘绳肌弯举',
  'Standing Hip Adduction': '站姿髋内收',
  'Standing Incline Cable Flyes': '站姿上斜飞鸟',
  'Standing Leg Extension': '站姿腿屈伸',
  'Standing Row': '站姿划船',
  'Standing Shrug': '哑铃耸肩',
  'Standing Triangle Straddle Bends': '站姿三角跨腿侧弯',
  'Standing Trunk Rotation': '站姿躯干旋转',
  'Step Stretch': '台阶小腿拉伸',
  'Straight Arm Pressdown': '直臂下压',
  'Suitcase Carry': '手提箱行走',
  'Sumo Rotational Squats': '相扑旋转深蹲',
  'Supine Bicycle Crunches': '仰卧自行车卷腹',
  'Supine IT Band Stretch': '仰卧髂胫束拉伸',
  'Supine Shoulder Roll': '仰卧稳定球肩滚',
  'Supine Spinal Twist with Rib Grab and Progressions': '仰卧脊柱旋转配合肋骨抓握',
  'Swing': '壶铃摆荡',
  'Toe Taps': 'BOSU 点脚',
  'Triceps Extension': '哑铃三头伸展',
  'TRX Assisted Cross-over Lunge with Arm Raise': 'TRX 辅助交叉弓步配合手臂上举',
  'TRX Assisted Side Lunge with Arm Raise': 'TRX 辅助侧弓步配合手臂上举',
  'Tuck Jump': '收腿跳',
  'V-twist': 'BOSU V 字转体',
  'V-ups': 'V 字起坐',
  'Vertical Toe Touches': '竖腿触脚趾',
  'Walking Lunges with Twists': '行走弓步配合旋转',
}

const normalizeSpaces = (value: string) => value.replace(/\s+/g, ' ').trim()

const phraseMap: Array<[string, string]> = [
  ['Agility Ladder', '敏捷梯'],
  ['Alternate', '交替'],
  ['Alternating', '交替'],
  ['Asynchronous', '交替'],
  ['Barbell', '杠铃'],
  ['Bear Crawl', '熊爬'],
  ['Bent Knee', '屈膝'],
  ['Bent-over', '俯身'],
  ['Bicep', '二头'],
  ['BOSU', 'BOSU'],
  ['Bottom-up', '底朝上'],
  ['Bulgarian', '保加利亚'],
  ['Burpee', '波比跳'],
  ['Calf', '提踵'],
  ['Chest', '胸部'],
  ['Chin-up', '引体向上'],
  ['Clean and Press', '高翻推举'],
  ['Clean', '高翻'],
  ['Cobra', '眼镜蛇'],
  ['Curl', '弯举'],
  ['Deadlift', '硬拉'],
  ['Decline', '下斜'],
  ['Double', '双'],
  ['Forward', '前向'],
  ['Front', '前'],
  ['Glute', '臀部'],
  ['Halo', '绕头光环'],
  ['Hammer', '锤式'],
  ['High', '高位'],
  ['Hover', '悬停'],
  ['Inchworms', '毛毛虫爬行'],
  ['Jammers', '冲击推'],
  ['Jump', '跳'],
  ['Jumps', '跳'],
  ['Kickback', '后伸'],
  ['Kneeling', '跪姿'],
  ['Ladder', '梯'],
  ['Lateral', '侧向'],
  ['Leg', '腿'],
  ['Lunge', '弓步'],
  ['Modified', '简化'],
  ['Mountain Climbers', '登山跑'],
  ['Overhead', '过顶'],
  ['Plank', '平板支撑'],
  ['Pressdown', '下压'],
  ['Press', '推举'],
  ['Pull', '拉'],
  ['Push Jerk', '借力挺举'],
  ['Push Press', '借力推举'],
  ['Push-off', '蹬离'],
  ['Push-up', '俯卧撑'],
  ['Raise', '上举'],
  ['Renegade Row', '俯撑交替划船'],
  ['Reverse', '反向'],
  ['Roll-out', '滚出'],
  ['Rotation', '旋转'],
  ['Rotational', '旋转'],
  ['Row', '划船'],
  ['Russian Twist', '俄罗斯转体'],
  ['Shuffle', '滑步'],
  ['Side', '侧'],
  ['Single-arm', '单臂'],
  ['Single-leg', '单腿'],
  ['Single', '单侧'],
  ['Split Squat', '分腿蹲'],
  ['Squat', '深蹲'],
  ['Step-up', '登台阶'],
  ['Stretch', '拉伸'],
  ['Swing', '摆动'],
  ['Triceps', '三头'],
  ['Twist', '转体'],
  ['Uppercut', '上勾拳'],
  ['Walk', '行走'],
  ['Warrior', '战士式'],
  ['Wave', '波浪'],
  ['Waves', '波浪'],
  ['Windmill', '风车'],
  ['Wood Chop', '伐木式'],
]

const sortedPhraseMap = [...phraseMap].sort((a, b) => b[0].length - a[0].length)

const exactTipMap: Record<string, string> = {
  'Move with control': '全程控制动作速度',
  'Keep the trunk braced': '保持核心收紧稳定',
  'Use a pain-free range of motion': '在无疼痛的活动范围内完成动作',
}

const titleToChinese = (value: string) => {
  const exact = exactExerciseNameMap[value]
  if (exact) return exact

  let result = value
  for (const [source, target] of sortedPhraseMap) {
    const escaped = source.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    result = result.replace(new RegExp(escaped, 'gi'), target)
  }

  result = result
    .replace(/\bwith\b/gi, '配合')
    .replace(/\band\b/gi, '与')
    .replace(/\bto\b/gi, '接')
    .replace(/\bof\b/gi, '')
    .replace(/:\s*/g, '：')
    .replace(/\s*-\s*/g, ' ')
    .replace(/\s{2,}/g, ' ')

  return normalizeSpaces(result)
}

export const translateExerciseName = (name?: string) => {
  if (!name) return ''
  return titleToChinese(name)
}

export const translateTarget = (target?: string) => {
  if (!target) return ''
  return target
    .split(',')
    .map(item => bodyPartMap[item.trim()] || item.trim())
    .join(' · ')
}

export const translateMuscle = (muscle?: string) => {
  if (!muscle) return ''
  return muscleMap[muscle.trim()] || muscle.trim()
}

export const translateMuscles = (muscles?: string[]) => {
  if (!Array.isArray(muscles)) return []
  return muscles.map(translateMuscle)
}

export const translateExerciseDescription = (exercise: any) => {
  const target = translateTarget(exercise?.target)
  if (!target) return exercise?.description || ''
  return `ACE 动作库参考动作，主要锻炼 ${target}。`
}

export const translateTips = (tips?: string[]) => {
  if (!Array.isArray(tips)) return []
  return tips.map(tip => exactTipMap[tip] || tip)
}

export const localizeExercise = (exercise: any) => ({
  ...exercise,
  displayName: translateExerciseName(exercise?.name),
  displayNameEn: exercise?.name || '',
  displayTarget: translateTarget(exercise?.target),
  displayPrimaryMuscle: translateMuscle(exercise?.primaryMuscle),
  displaySecondaryMuscles: translateMuscles(exercise?.secondaryMuscles || []),
  displayDescription: translateExerciseDescription(exercise),
  displayTips: translateTips(exercise?.tips || []),
})
